before_install:
    - sudo apt-get update -qq
    - sudo apt-get install -qq libxml2-utils
script:
    - xmllint --schema http://iatistandard.org/104/schema/downloads/iati-activities-schema.xsd --noout en/activity-standard/*.xml
    - xmllint --schema http://iatistandard.org/104/schema/downloads/iati-organisations-schema.xsd --noout en/organisation-standard/*.xml
